let datos = ['CARLOS ANDRES FANDIÑO RUEDA', 'JORGE ALBERTO RODRIGUEZ PAEZ', 'EDGAR LEONARDO RODRIGUEZ VASQUEZ', 'KELLY JOHANA VERGARA TORRES', 'LINA MARÍA RODRÍGUEZ RAMÍREZ', 'JOHN JAIRO ORJUELA ESPINOSA', 'JHON FAVER MACHADO ALAPE', 'FRANCISCO JAVIER TORRES VILLAMOR', 'ANDRES FELIPE GIRALDO', 'EDWIN GERMAN VILLALBA GONZALEZ', 'CRISTIAN ORLANDO ROMERO ACOSTA', 'CRISTIAN DAVID SAINEA CÉSPEDES', 'DANIEL CAMILO RAMIREZ MARTINEZ', 'ALEJANDRO RIVAS LOPEZ', 'DIANA GARCIA SANDOVAL', 'MARCOS ORTIZ']

function estudiantes(datos) {
    let indiceAleatorio = Math.floor(Math.random() * datos.length);
    return datos[indiceAleatorio];
}
//console.log(estudiantes(datos));

